import { CommunityCardProps, PersonCardProps } from "./interfaces/commonInterfaces";

export const sampleCommunityData: CommunityCardProps[] = [
  {
    id: 'c1',
    name: "React Native Developers",
    lastMessage: "Has anyone tried the new fabric architecture yet?",
    messagedPersonName: "Jordan",
    unreadMessageCount: 5,
    communityAvatar: "https://ui-avatars.com/api/?name=React+Native&background=61dafb&color=fff",
    limit: 3, // Optional limit for this specific card
    users: [
      { id: 'u1', uri: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=60' },
      { id: 'u2', uri: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=60' },
      { id: 'u3', uri: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=100&auto=format&fit=crop&q=60' },
      { id: 'u4', uri: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=100&auto=format&fit=crop&q=60' },
    ],
  },
  {
    id: 'c2',
    name: "Weekend Football",
    lastMessage: "I'll bring the extra ball, see you at 5!",
    messagedPersonName: "Mike",
    unreadMessageCount: 0, // No unread badge should show
    communityAvatar: "https://www.independent.com.mt/file.aspx?f=167366&width=630&height=340",
    limit: 4,
    users: [
      { id: 'u5', uri: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=100&auto=format&fit=crop&q=60' },
      { id: 'u6', uri: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=60' },
      { id: 'u7', uri: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=60' },
    ],
  },
  {
    id: 'c3',
    name: "Design Team",
    lastMessage: "Can we review the Figma prototypes?",
    messagedPersonName: "Sarah",
    unreadMessageCount: 12,
    communityAvatar: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=100&auto=format&fit=crop&q=60",
    // limit is undefined here, your component should use its default
    users: [
      { id: 'u8', uri: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&auto=format&fit=crop&q=60' },
      { id: 'u9', uri: 'https://images.unsplash.com/photo-1633332755192-727a05c4013d?w=100&auto=format&fit=crop&q=60' },
      { id: 'u10', uri: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&auto=format&fit=crop&q=60' },
      { id: 'u11', uri: 'https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?w=100&auto=format&fit=crop&q=60' },
      { id: 'u12', uri: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=60' },
      { id: 'u13', uri: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&auto=format&fit=crop&q=60' },
    ],
  },
];

export const chatList: PersonCardProps[] = [
  {
    id: "1",
    personImage: "https://i.pravatar.cc/400?u=1",
    name: "Alex Johnson",
    lastMessage: "Hey, are we still on for lunch?",
    unreadMessageCount: 2,
    lastMessageTime: "10:30 AM",
    isTyping: false,
    isPined: true,
  },
  {
    id: "2",
    personImage: "https://i.pravatar.cc/400?u=2",
    name: "Sarah Williams",
    lastMessage: "I just sent over the design files.",
    unreadMessageCount: 0,
    lastMessageTime: "9:15 AM",
    isTyping: true,
  },
  {
    id: "3",
    personImage: "https://i.pravatar.cc/400?u=3",
    name: "Michael Chen",
    lastMessage: "Can you check the PR when you have a sec?",
    unreadMessageCount: 5,
    lastMessageTime: "Yesterday",
    isTyping: false,
  },
  {
    id: "4",
    personImage: "https://i.pravatar.cc/400?u=4",
    name: "Emily Davis",
    lastMessage: "lol that was hilarious 😂",
    lastMessageTime: "Yesterday",
    isTyping: false,
  },
  {
    id: "5",
    personImage: "https://i.pravatar.cc/400?u=5",
    name: "David Miller",
    lastMessage: "Let me know when you arrive.",
    unreadMessageCount: 1,
    lastMessageTime: "Mon",
    isTyping: false,
  },
  {
    id: "6",
    personImage: "https://i.pravatar.cc/400?u=6",
    name: "Jessica Wilson",
    lastMessage: "typing...",
    unreadMessageCount: 0,
    lastMessageTime: "Just now",
    isTyping: true,
  },
  {
    id: "7",
    personImage: "https://i.pravatar.cc/400?u=7",
    name: "James Anderson",
    lastMessage: "The meeting has been rescheduled to 3 PM.",
    lastMessageTime: "Sun",
    isTyping: false,
  },
  {
    id: "8",
    personImage: "https://i.pravatar.cc/400?u=8",
    name: "Olivia Martinez",
    lastMessage: "Thanks so much for your help!",
    unreadMessageCount: 0,
    lastMessageTime: "Oct 25",
    isTyping: false,
  },
  {
    id: "9",
    personImage: "https://i.pravatar.cc/400?u=9",
    name: "William Taylor",
    lastMessage: "Did you watch the game last night?",
    unreadMessageCount: 3,
    lastMessageTime: "Oct 24",
    isTyping: false,
  },
  {
    id: "10",
    personImage: "https://i.pravatar.cc/400?u=10",
    name: "Sophia Thomas",
    lastMessage: "Sending the invoice now.",
    lastMessageTime: "Oct 22",
    isTyping: false,
  },
  {
    id: "11",
    personImage: "https://i.pravatar.cc/400?u=11",
    name: "Daniel Hernandez",
    lastMessage: "Where is the location?",
    unreadMessageCount: 1,
    lastMessageTime: "11:45 AM",
    isTyping: false,
  },
  {
    id: "12",
    personImage: "https://i.pravatar.cc/400?u=12",
    name: "Isabella Moore",
    lastMessage: "Sounds good to me.",
    lastMessageTime: "Yesterday",
    isTyping: false,
  },
  {
    id: "13",
    personImage: "https://i.pravatar.cc/400?u=13",
    name: "Joseph Martin",
    lastMessage: "I'll call you in 5 minutes.",
    unreadMessageCount: 0,
    lastMessageTime: "10:05 AM",
    isTyping: true,
  },
  {
    id: "14",
    personImage: "https://i.pravatar.cc/400?u=14",
    name: "Mia Jackson",
    lastMessage: "Happy Birthday! 🎂",
    unreadMessageCount: 1,
    lastMessageTime: "Yesterday",
    isTyping: false,
  },
  {
    id: "15",
    personImage: "https://i.pravatar.cc/400?u=15",
    name: "Henry Thompson",
    lastMessage: "Please review the attached document.",
    lastMessageTime: "Mon",
    isTyping: false,
  },
  {
    id: "16",
    personImage: "https://i.pravatar.cc/400?u=16",
    name: "Charlotte White",
    lastMessage: "See you at the party!",
    unreadMessageCount: 0,
    lastMessageTime: "Fri",
    isTyping: false,
  },
  {
    id: "17",
    personImage: "https://i.pravatar.cc/400?u=17",
    name: "Alexander Lopez",
    lastMessage: "Do we need to bring anything?",
    unreadMessageCount: 4,
    lastMessageTime: "Thu",
    isTyping: false,
  },
  {
    id: "18",
    personImage: "https://i.pravatar.cc/400?u=18",
    name: "Amelia Lee",
    lastMessage: "Okay, got it.",
    lastMessageTime: "Wed",
    isTyping: false,
  },
  {
    id: "19",
    personImage: "https://i.pravatar.cc/400?u=19",
    name: "Benjamin Gonzalez",
    lastMessage: "Are you free for a quick call?",
    unreadMessageCount: 0,
    lastMessageTime: "Tue",
    isTyping: true,
  },
  {
    id: "20",
    personImage: "https://i.pravatar.cc/400?u=20",
    name: "Harper Harris",
    lastMessage: "No worries, take your time.",
    lastMessageTime: "Mon",
    isTyping: false,
  },
];